#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
  export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=gnome-flashback-xmonad-custom --disable-acceleration-check "$@"
